name: Security Scan
on:
  push:
    branches: [main,test]
  pull_request:
    branches: [main,test]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write # For SARIF upload

    steps:
      - uses: actions/checkout@v6

      - name: Run Microsoft Security DevOps
        uses: microsoft/security-devops-action@latest
        id: msdo
        with:
          policy: 'microsoft'

      - name: Upload results to Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.msdo.outputs.sarifFile }}
      
      - name: Upload SARIF as an Artifact
        uses: actions/upload-artifact@v5
        with:
          name: sarif-file
          path: ${{ steps.msdo.outputs.sarifFile }}
