name: Snyk Infrastructure as Code
on: 
  pull_request: 
    branches: [main]
    paths: 'terraform/**'
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run Snyk to check Kubernetes manifest file for issues
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=low --sarif-file-output=terraform.snyk.result

      - name: Upload sarif file to Github Code scanning
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: terraform.snyk.result
